const PDFDocument = require('pdfkit');

const PRIORITY_LABELS = { critical: 'Critical', important: 'Important', optional: 'Optional' };

function addHeading(doc, text) {
  doc.moveDown(0.8).fontSize(16).fillColor('#20241F').text(text, { underline: false }).moveDown(0.3);
  doc.moveTo(doc.x, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).strokeColor('#C6862E').lineWidth(1.5).stroke();
  doc.moveDown(0.4);
}

function addModuleSection(doc, title, mod) {
  if (!mod) return;
  addHeading(doc, `${title} — ${mod.score}/10`);
  doc.fontSize(10).fillColor('#20241F');
  if (mod.strengths?.length) {
    doc.font('Helvetica-Bold').text('Strengths:');
    doc.font('Helvetica');
    mod.strengths.forEach((s) => doc.text(`• ${s}`));
    doc.moveDown(0.3);
  }
  if (mod.weaknesses?.length) {
    doc.font('Helvetica-Bold').text('Weaknesses:');
    doc.font('Helvetica');
    mod.weaknesses.forEach((s) => doc.text(`• ${s}`));
    doc.moveDown(0.3);
  }
  if (mod.recommendations?.length) {
    doc.font('Helvetica-Bold').text('Recommendations:');
    doc.font('Helvetica');
    mod.recommendations.forEach((r) => {
      doc.text(`[${PRIORITY_LABELS[r.priority] || r.priority}] ${r.problem}`);
      doc.fillColor('#555').text(`  Why it matters: ${r.reason}`);
      if (r.current) doc.text(`  Current: ${r.current}`);
      doc.text(`  Suggested: ${r.suggested}`);
      doc.text(`  Action: ${r.action}`);
      doc.fillColor('#20241F').moveDown(0.2);
    });
  }
}

/**
 * @param {import('stream').Writable} outputStream - e.g. an Express response
 * @param {object} report - { overallScore, label, breakdown, analysis, jobMatch, meta }
 */
function generatePdfReport(outputStream, report) {
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(outputStream);

  doc.fontSize(22).fillColor('#20241F').font('Helvetica-Bold').text('AI CV Analyzer — Report');
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(`Generated ${new Date().toISOString()}`);
  doc.moveDown(1);

  doc.fontSize(40).fillColor('#2B6E63').font('Helvetica-Bold').text(`${report.overallScore} / 10`);
  doc.fontSize(14).fillColor('#20241F').font('Helvetica').text(report.label);
  doc.moveDown(0.5);

  addHeading(doc, 'Score Breakdown');
  doc.fontSize(10).fillColor('#20241F');
  report.breakdown.forEach((b) => {
    if (b.score !== null) doc.text(`${b.label}: ${b.score}/10  (weight ${(b.weight * 100).toFixed(0)}%)`);
  });

  if (report.analysis.overallImpression) {
    addHeading(doc, 'Overall Impression');
    doc.fontSize(10).fillColor('#20241F').text(report.analysis.overallImpression);
  }

  if (report.analysis.topPriorityActions?.length) {
    addHeading(doc, 'Top Priority Actions');
    doc.fontSize(10).fillColor('#20241F');
    report.analysis.topPriorityActions.forEach((a, i) => doc.text(`${i + 1}. ${a}`));
  }

  addModuleSection(doc, 'ATS Compatibility', report.analysis.ats);
  addModuleSection(doc, 'Content Quality', report.analysis.content);
  addModuleSection(doc, 'Experience', report.analysis.experience);
  addModuleSection(doc, 'Skills', report.analysis.skills);
  addModuleSection(doc, 'Education', report.analysis.education);
  addModuleSection(doc, 'Structure', report.analysis.structure);
  addModuleSection(doc, 'Formatting', report.analysis.formatting);

  if (report.jobMatch) {
    addHeading(doc, `Job Match — ${report.jobMatch.matchPercentage}%`);
    doc.fontSize(10).fillColor('#20241F');
    if (report.jobMatch.matchingSkills?.length) doc.text(`Matching skills: ${report.jobMatch.matchingSkills.join(', ')}`);
    if (report.jobMatch.missingRequirements?.length) doc.text(`Missing requirements: ${report.jobMatch.missingRequirements.join(', ')}`);
    if (report.jobMatch.recommendedKeywords?.length) doc.text(`Recommended keywords: ${report.jobMatch.recommendedKeywords.join(', ')}`);
  }

  doc.moveDown(1);
  doc.fontSize(8).fillColor('#888').text(
    'This report is generated by an AI analysis tool. Scores and ATS compatibility are estimates, not guarantees ' +
    'of outcomes with any specific employer or applicant tracking system.'
  );

  doc.end();
}

module.exports = { generatePdfReport };
